// import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Registry as StyledComponentRegistry } from "./styles/registery";
import Header from "./components/common/Header/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentRegistry>
          <Header />
          {children}
        </StyledComponentRegistry>
      </body>
    </html>
  );
}
